/*
 * Cloud Functions entry for Kilowatch tips.
 * - Callable `generateTips` (own-home, optional force)
 * - Scheduled `autoGenerateTips` (hourly) for background regeneration + FCM
 * See docs/FEATURE_MAP.md (Tips & News) and ./lib/tipsCore.js for algorithms.
 */
const { initializeApp } = require("firebase-admin/app");
const { getDatabase } = require("firebase-admin/database");
const { onCall, HttpsError } = require("firebase-functions/v2/https");
const { onSchedule } = require("firebase-functions/v2/scheduler");
const { onValueWritten } = require("firebase-functions/v2/database");
const { defineSecret } = require("firebase-functions/params");
const {
  PROMPT_VERSION,
  monthKey,
  previousMonthKey,
  isoWeekKey,
  formatDate,
  addDays,
  startOfDay,
  buildCompactStats,
  buildRuleBasedTips,
  callOpenAiTips,
  evaluateTipsEligibility,
} = require("./lib/tipsCore");
const { notifyTipsAutoGenerated } = require("./lib/tipsNotify");
const {
  transferHomeOwnershipAdmin,
} = require("./lib/transferHomeOwnership");
const {
  migrateTransferredHomeIfNeeded,
} = require("./lib/homeOwnershipMigrate");

initializeApp();

const RTDB_INSTANCE = "energy-monitoring-system-f182d-default-rtdb";

const openaiApiKey = defineSecret("OPENAI_API_KEY");

/** Load only the last ~14 daily history buckets needed for tip stats. */
async function loadHistorySlice(db, ownerUid, deviceIds, now = new Date()) {
  const start = addDays(startOfDay(now), -13);
  const keys = [];
  let cursor = startOfDay(start);
  const end = startOfDay(now);
  while (cursor <= end) {
    keys.push(formatDate(cursor));
    cursor = addDays(cursor, 1);
  }

  const historyByDevice = {};
  await Promise.all(
    deviceIds.map(async (deviceId) => {
      const snap = await db.ref(`history/${ownerUid}/${deviceId}/daily`).get();
      const dailyAll = snap.val() || {};
      const daily = {};
      keys.forEach((key) => {
        if (dailyAll[key]) daily[key] = dailyAll[key];
      });
      historyByDevice[deviceId] = { daily };
    })
  );
  return historyByDevice;
}

/** Gather rooms/appliances/live/history/rate into compact tip-input stats. */
async function buildStatsForOwner(db, ownerUid) {
  const [
    roomsSnap,
    appliancesSnap,
    devicesSnap,
    liveSnap,
    profileSnap,
    kilosaveSnap,
  ] = await Promise.all([
    db.ref(`rooms/${ownerUid}`).get(),
    db.ref(`appliances/${ownerUid}`).get(),
    db.ref(`devices/${ownerUid}`).get(),
    db.ref(`live/${ownerUid}`).get(),
    db.ref(`users/${ownerUid}`).get(),
    db.ref(`kilosave/${ownerUid}/settings`).get(),
  ]);

  const roomsMap = roomsSnap.val() || {};
  const appliancesMap = appliancesSnap.val() || {};
  const devicesMap = devicesSnap.val() || {};
  const liveMap = liveSnap.val() || {};
  const profile = profileSnap.val() || {};
  const rate = Number(profile.electricityRate || profile.rate || 0);
  const deviceIds = [
    ...new Set(
      Object.values(appliancesMap)
        .map((a) => a?.deviceId)
        .filter(Boolean)
    ),
  ];
  const historyByDevice = await loadHistorySlice(db, ownerUid, deviceIds);

  const stats = buildCompactStats({
    roomsMap,
    appliancesMap,
    liveMap,
    historyByDevice,
    rate,
    kilosaveSettings: kilosaveSnap.val(),
  });

  return {
    stats,
    roomsMap,
    appliancesMap,
    devicesMap,
    historyByDevice,
  };
}

function isFreshCache(cached, stats) {
  const rooms = normalizeRooms(cached?.rooms);
  const layoutOk = cached?.layoutFingerprint
    ? cached.layoutFingerprint === stats.layoutFingerprint
    : false;
  return (
    cached &&
    cached.promptVersion === PROMPT_VERSION &&
    layoutOk &&
    cached.weekKey === stats.weekKey &&
    rooms.length > 0
  );
}

/** RTDB sometimes returns arrays as objects — always normalize for clients. */
function normalizeRooms(rooms) {
  if (Array.isArray(rooms)) return rooms.filter(Boolean);
  if (rooms && typeof rooms === "object") {
    return Object.keys(rooms)
      .sort((a, b) => Number(a) - Number(b))
      .map((key) => rooms[key])
      .filter(Boolean);
  }
  return [];
}

function sanitizeTipsPayload(payload, { cacheHit = false } = {}) {
  if (!payload || typeof payload !== "object") {
    return {
      generatedAt: Date.now(),
      rooms: [],
      source: "empty",
      cacheHit,
      promptVersion: PROMPT_VERSION,
    };
  }
  return {
    ...payload,
    rooms: normalizeRooms(payload.rooms),
    summary: payload.summary || {
      weeksDone: 0,
      avgPerWeek: "₱0.00",
      appliances: 0,
    },
    cacheHit,
  };
}

/**
 * Core generate path shared by callable + scheduler.
 * @returns {{ payload, created: boolean, kind: 'first'|'weekly'|null }}
 */
async function generateTipsForOwner(
  db,
  ownerUid,
  { force = false, apiKey = null, auto = false, adminForce = false } = {}
) {
  const key = monthKey();
  const prevKey = previousMonthKey();
  const weekKey = isoWeekKey();
  const cacheRef = db.ref(`tips/${ownerUid}/months/${key}`);
  const prevCacheRef = db.ref(`tips/${ownerUid}/months/${prevKey}`);
  const [cachedSnap, prevCachedSnap] = await Promise.all([
    cacheRef.get(),
    prevCacheRef.get(),
  ]);
  const cached = cachedSnap.val();
  const prevCached = prevCachedSnap.val();

  const { stats, appliancesMap, devicesMap, historyByDevice } =
    await buildStatsForOwner(db, ownerUid);

  const freshCached = isFreshCache(cached, stats)
    ? cached
    : isFreshCache(prevCached, stats)
      ? prevCached
      : null;

  // Admin Feature Demo skips always regenerate even if this week is fresh.
  if (!adminForce && !force && freshCached) {
    return {
      payload: sanitizeTipsPayload(freshCached, { cacheHit: true }),
      created: false,
      kind: null,
      weekKey: stats.weekKey || weekKey,
    };
  }

  if (!adminForce && force && freshCached) {
    const err = new Error(
      "Tips were already generated for this week. Come back next week."
    );
    err.code = "failed-precondition";
    throw err;
  }

  const eligibility = evaluateTipsEligibility({
    appliancesMap,
    devicesMap,
    historyByDevice,
  });
  if (!eligibility.canGenerate) {
    const err = new Error(eligibility.message || "Tips are not ready yet.");
    err.code = "failed-precondition";
    throw err;
  }

  const hadAnyTips =
    normalizeRooms(cached?.rooms).length > 0 ||
    normalizeRooms(prevCached?.rooms).length > 0;
  const kind = hadAnyTips ? "weekly" : "first";

  let payload;
  if (!stats.rooms.length) {
    payload = sanitizeTipsPayload(
      {
        ...buildRuleBasedTips(stats),
        rooms: [],
        source: "empty",
      },
      { cacheHit: false }
    );
  } else {
    try {
      if (!apiKey) throw new Error("OPENAI_API_KEY missing");
      payload = await callOpenAiTips(stats, apiKey);
    } catch (error) {
      console.warn("OpenAI tips failed, using rule-based", error?.message || error);
      payload = buildRuleBasedTips(stats);
    }
    payload = sanitizeTipsPayload(payload, { cacheHit: false });
  }

  payload = {
    ...payload,
    autoGenerated: Boolean(auto),
    autoGenerateKind: kind,
    generatedAt: Date.now(),
  };

  await cacheRef.set(payload);
  return {
    payload,
    created: true,
    kind,
    weekKey: payload.weekKey || stats.weekKey || weekKey,
  };
}

/**
 * Safety net for old app builds that flip meta.ownerUid without migrating
 * rooms/devices/claims. When the path owner no longer matches meta.ownerUid
 * and gear is still under the old path, move it onto the new owner.
 */
exports.onHomeMetaWritten = onValueWritten(
  {
    ref: "/homes/{homeId}/meta",
    instance: RTDB_INSTANCE,
    region: "asia-southeast1",
  },
  async (event) => {
    const homeId = event.params.homeId;
    const after = event.data.after.val();
    const before = event.data.before.val();
    if (!after?.ownerUid) return null;
    if (before?.ownerUid === after.ownerUid) return null;
    if (after.ownerUid === homeId) return null;

    const db = getDatabase();
    try {
      const result = await migrateTransferredHomeIfNeeded(db, homeId);
      console.log(
        `onHomeMetaWritten home=${homeId} owner=${after.ownerUid} result=${JSON.stringify(
          result
        )}`
      );
      return result;
    } catch (error) {
      console.error(
        `onHomeMetaWritten failed home=${homeId}`,
        error?.message || error
      );
      return null;
    }
  }
);

/**
 * Callable: transferHomeOwnership
 * Previous owner leaves the home and gets a fresh empty home.
 * If the home path is still their uid, migrate rooms/devices onto the new owner.
 */
exports.transferHomeOwnership = onCall(
  {
    region: "asia-southeast1",
    timeoutSeconds: 120,
    memory: "512MiB",
  },
  async (request) => {
    if (!request.auth?.uid) {
      throw new HttpsError("unauthenticated", "Sign in required.");
    }

    const homeId = String(request.data?.homeId || "").trim();
    const toUid = String(request.data?.toUid || "").trim();
    if (!homeId || !toUid) {
      throw new HttpsError("invalid-argument", "Missing home or member.");
    }

    const db = getDatabase();
    try {
      return await transferHomeOwnershipAdmin(db, {
        homeId,
        fromUid: request.auth.uid,
        toUid,
      });
    } catch (error) {
      if (error instanceof HttpsError) throw error;
      console.error("transferHomeOwnership failed", error);
      throw new HttpsError(
        "internal",
        error?.message || "Unable to transfer ownership."
      );
    }
  }
);

/**
 * Callable: generateTips
 * - Own home only
 * - Manual/client auto: requires ≥1 week since earliest plug + enough history
 * - Cooldown: one generate per ISO week per layout (add/delete resets layout)
 */
exports.generateTips = onCall(
  {
    region: "asia-southeast1",
    secrets: [openaiApiKey],
    timeoutSeconds: 60,
    memory: "256MiB",
  },
  async (request) => {
    if (!request.auth?.uid) {
      throw new HttpsError("unauthenticated", "Sign in required.");
    }

    const uid = request.auth.uid;
    const force = Boolean(request.data?.force);
    const ownerUid = String(request.data?.ownerUid || uid);

    if (ownerUid !== uid) {
      throw new HttpsError(
        "permission-denied",
        "Kilo tips can only be generated for your own home."
      );
    }

    const db = getDatabase();
    try {
      const result = await generateTipsForOwner(db, ownerUid, {
        force,
        apiKey: openaiApiKey.value(),
        auto: Boolean(request.data?.auto),
      });

      if (result.created) {
        try {
          await notifyTipsAutoGenerated(ownerUid, {
            weekKey: result.weekKey,
            kind: result.kind || "weekly",
          });
        } catch (notifyErr) {
          console.warn("Tips notify failed:", notifyErr?.message || notifyErr);
        }
      }

      return result.payload;
    } catch (error) {
      if (error?.code === "failed-precondition") {
        throw new HttpsError("failed-precondition", error.message);
      }
      throw error;
    }
  }
);

/**
 * Hourly scan: auto-generate tips for eligible homes even if the app is closed.
 * Notifies owner + household members with the home name in the push.
 */
exports.autoGenerateTips = onSchedule(
  {
    schedule: "every 60 minutes",
    timeZone: "Asia/Manila",
    region: "asia-southeast1",
    secrets: [openaiApiKey],
    timeoutSeconds: 540,
    memory: "512MiB",
  },
  async () => {
    const db = getDatabase();
    const appliancesRoot = (await db.ref("appliances").get()).val() || {};
    const ownerUids = Object.keys(appliancesRoot);
    let checked = 0;
    let created = 0;
    let notified = 0;

    // Cap per run so we stay inside the timeout on large fleets.
    const batch = ownerUids.slice(0, 40);
    for (const ownerUid of batch) {
      checked += 1;
      try {
        const result = await generateTipsForOwner(db, ownerUid, {
          force: false,
          apiKey: openaiApiKey.value(),
          auto: true,
        });
        if (!result.created) continue;
        created += 1;
        const delivery = await notifyTipsAutoGenerated(ownerUid, {
          weekKey: result.weekKey,
          kind: result.kind || "weekly",
        });
        notified += Number(delivery?.sent || 0);
        console.log(
          `auto tips ${ownerUid} kind=${result.kind} fcm=${delivery?.sent || 0}`
        );
      } catch (error) {
        if (error?.code === "failed-precondition") continue;
        console.warn(`auto tips failed ${ownerUid}:`, error?.message || error);
      }
    }

    console.log(
      `autoGenerateTips checked=${checked} created=${created} fcm=${notified}`
    );
    return { checked, created, notified };
  }
);

const TIPS_ADMIN_STUCK_MS = 3 * 60 * 1000;
/** Poller only touches leftovers older than this (callable owns fresh Skips). */
const TIPS_ADMIN_POLLER_MIN_AGE_MS = 2 * 60 * 1000;

function tipsAdminTriggerStuck(trigger, nowMs = Date.now()) {
  if (trigger?.status !== "running") return false;
  const started = Number(trigger.startedAt || trigger.createdAt || 0);
  return !started || nowMs - started >= TIPS_ADMIN_STUCK_MS;
}

async function readTipsAdminTrigger(db, ownerUid) {
  return (await db.ref(`tips/${ownerUid}/adminDemo/generateTrigger`).get()).val();
}

async function waitForTipsAdminTriggerDone(
  db,
  ownerUid,
  createdAt,
  timeoutMs = 20_000
) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const trigger = await readTipsAdminTrigger(db, ownerUid);
    if (!trigger || Number(trigger.createdAt) !== Number(createdAt)) {
      return null;
    }
    if (trigger.status === "done" || trigger.status === "failed") {
      return trigger;
    }
    await new Promise((resolve) => setTimeout(resolve, 1000));
  }
  return readTipsAdminTrigger(db, ownerUid);
}

/**
 * Process one pending adminDemo.generateTrigger (Skip 7 / Skip 14).
 * Claim → generate → FCM → mark done (never leave a bare trigger after work).
 */
async function processTipsAdminTrigger(db, ownerUid, trigger, apiKey) {
  const createdAt = Number(trigger?.createdAt || 0);
  if (!createdAt) return { skipped: true, reason: "missing" };
  const ageMs = Date.now() - createdAt;
  if (!(ageMs >= 0 && ageMs <= 60 * 60 * 1000)) {
    return { skipped: true, reason: "stale" };
  }
  if (trigger.status === "done") {
    return {
      skipped: true,
      reason: "done",
      sent: Number(trigger.fcmSent || 0),
      kind: trigger.kind || null,
    };
  }
  if (trigger.status === "failed") {
    return { skipped: true, reason: "failed" };
  }
  if (trigger.status === "running" && !tipsAdminTriggerStuck(trigger)) {
    return { skipped: true, reason: "running" };
  }

  const triggerRef = db.ref(`tips/${ownerUid}/adminDemo/generateTrigger`);
  const claimed = await triggerRef.transaction((current) => {
    if (!current?.createdAt || Number(current.createdAt) !== createdAt) return;
    if (current.status === "done" || current.status === "failed") return;
    if (current.status === "running" && !tipsAdminTriggerStuck(current)) {
      return;
    }
    return { ...current, status: "running", startedAt: Date.now() };
  });
  if (!claimed.committed) {
    const latest = claimed.snapshot?.val?.() || (await triggerRef.get()).val();
    if (Number(latest?.createdAt) === createdAt && latest?.status === "done") {
      return {
        skipped: true,
        reason: "done",
        sent: Number(latest.fcmSent || 0),
        kind: latest.kind || null,
      };
    }
    if (
      Number(latest?.createdAt) === createdAt &&
      latest?.status === "running" &&
      !tipsAdminTriggerStuck(latest)
    ) {
      return { skipped: true, reason: "running" };
    }
    return { skipped: true, reason: "claim" };
  }

  const claimedTrigger = claimed.snapshot.val() || trigger;
  try {
    const result = await generateTipsForOwner(db, ownerUid, {
      force: false,
      adminForce: true,
      apiKey,
      auto: true,
    });
    const kind =
      claimedTrigger.kind === "first" || claimedTrigger.kind === "weekly"
        ? claimedTrigger.kind
        : result.kind || "weekly";
    const delivery = await notifyTipsAutoGenerated(ownerUid, {
      weekKey: result.weekKey,
      kind,
      notifyKey: `demo_${createdAt}`,
    });
    const fcmSent = Number(delivery?.sent || 0);
    await triggerRef.set({
      ...claimedTrigger,
      status: "done",
      kind,
      weekKey: result.weekKey || null,
      fcmSent,
      notifyReason: delivery?.reason || delivery?.skipped || null,
      finishedAt: Date.now(),
    });
    console.log(
      `tips admin trigger done home=${ownerUid} kind=${kind} fcm=${fcmSent}`
    );
    return { ok: true, sent: fcmSent, kind };
  } catch (error) {
    await triggerRef.set({
      ...claimedTrigger,
      status: "failed",
      failedAt: Date.now(),
      reason: String(error?.message || error).slice(0, 200),
    });
    throw error;
  }
}

/**
 * Admin callable: force-generate tips for any home + notify household.
 * Primary owner of Feature Demo Skip 7 / Skip 14 (poller is stale backup only).
 */
exports.adminGenerateTips = onCall(
  {
    region: "asia-southeast1",
    secrets: [openaiApiKey],
    timeoutSeconds: 180,
    memory: "512MiB",
  },
  async (request) => {
    if (!request.auth?.uid) {
      throw new HttpsError("unauthenticated", "Sign in required.");
    }
    const db = getDatabase();
    const adminSnap = await db.ref(`admins/${request.auth.uid}`).get();
    if (adminSnap.val() !== true) {
      throw new HttpsError("permission-denied", "Admin only.");
    }

    const ownerUid = String(request.data?.ownerUid || "").trim();
    if (!ownerUid) {
      throw new HttpsError("invalid-argument", "ownerUid required.");
    }
    const kindHint =
      request.data?.kind === "first" || request.data?.kind === "weekly"
        ? request.data.kind
        : "weekly";
    const createdAt = Number(request.data?.createdAt || Date.now());
    const apiKey = openaiApiKey.value();
    const triggerRef = db.ref(`tips/${ownerUid}/adminDemo/generateTrigger`);

    // Align RTDB trigger with this Skip click (idempotent for the same createdAt).
    let trigger = await readTipsAdminTrigger(db, ownerUid);
    if (!trigger || Number(trigger.createdAt) !== createdAt) {
      await triggerRef.set({
        createdAt,
        kind: kindHint,
        source: "adminGenerateTips",
      });
      trigger = await readTipsAdminTrigger(db, ownerUid);
    }

    try {
      // A few claim retries — RTDB transactions can abort under concurrent writes.
      let processed = null;
      for (let attempt = 0; attempt < 3; attempt += 1) {
        trigger = await readTipsAdminTrigger(db, ownerUid);
        if (!trigger || Number(trigger.createdAt) !== createdAt) {
          await triggerRef.set({
            createdAt,
            kind: kindHint,
            source: "adminGenerateTips",
          });
          trigger = await readTipsAdminTrigger(db, ownerUid);
        }
        processed = await processTipsAdminTrigger(
          db,
          ownerUid,
          trigger,
          apiKey
        );
        if (processed?.ok) {
          return {
            ok: true,
            kind: processed.kind,
            fcmSent: Number(processed.sent || 0),
            via: "trigger",
          };
        }
        if (processed?.reason === "done") {
          return {
            ok: true,
            kind: processed.kind || kindHint,
            fcmSent: Number(processed.sent || 0),
            via: "trigger-done",
          };
        }
        if (processed?.reason === "running" || processed?.reason === "claim") {
          break;
        }
        await new Promise((resolve) => setTimeout(resolve, 400));
      }

      if (processed?.reason === "running" || processed?.reason === "claim") {
        const done = await waitForTipsAdminTriggerDone(db, ownerUid, createdAt);
        if (done?.status === "done" && Number(done.createdAt) === createdAt) {
          return {
            ok: true,
            kind: done.kind || kindHint,
            fcmSent: Number(done.fcmSent || 0),
            via: "trigger-wait",
          };
        }
        if (done?.status === "failed" && Number(done.createdAt) === createdAt) {
          throw new HttpsError(
            "internal",
            done.reason || "Tips admin generate failed."
          );
        }
        // Still stuck — reclaim once more (covers abandoned "running").
        const latest = await readTipsAdminTrigger(db, ownerUid);
        if (latest && Number(latest.createdAt) === createdAt) {
          const retry = await processTipsAdminTrigger(
            db,
            ownerUid,
            latest,
            apiKey
          );
          if (retry?.ok) {
            return {
              ok: true,
              kind: retry.kind,
              fcmSent: Number(retry.sent || 0),
              via: "trigger-retry",
            };
          }
          if (retry?.reason === "done") {
            return {
              ok: true,
              kind: retry.kind || kindHint,
              fcmSent: Number(retry.sent || 0),
              via: "trigger-done",
            };
          }
        }
      }

      // Last resort: generate + notify directly, then stamp the trigger done.
      const result = await generateTipsForOwner(db, ownerUid, {
        force: false,
        adminForce: true,
        apiKey,
        auto: true,
      });
      const kind = kindHint || result.kind || "weekly";
      const delivery = await notifyTipsAutoGenerated(ownerUid, {
        weekKey: result.weekKey,
        kind,
        notifyKey: `demo_${createdAt}`,
      });
      const fcmSent = Number(delivery?.sent || 0);
      await triggerRef.set({
        createdAt,
        kind,
        source: "adminGenerateTips-direct",
        status: "done",
        weekKey: result.weekKey || null,
        fcmSent,
        finishedAt: Date.now(),
      });
      return {
        ok: true,
        kind,
        weekKey: result.weekKey,
        fcmSent,
        via: "direct",
      };
    } catch (error) {
      if (error instanceof HttpsError) throw error;
      if (error?.code === "failed-precondition") {
        throw new HttpsError("failed-precondition", error.message);
      }
      throw error;
    }
  }
);

/**
 * Stale-only backup: process Skip triggers the callable never finished
 * (age ≥ 2 minutes, or stuck "running"). Avoids racing fresh Skip clicks.
 */
exports.pollTipsAdminTriggers = onSchedule(
  {
    schedule: "every 1 minutes",
    timeZone: "Asia/Manila",
    region: "asia-southeast1",
    secrets: [openaiApiKey],
    timeoutSeconds: 300,
    memory: "512MiB",
  },
  async () => {
    const db = getDatabase();
    const tipsRoot = (await db.ref("tips").get()).val() || {};
    let processed = 0;
    let notified = 0;
    const nowMs = Date.now();

    for (const [ownerUid, node] of Object.entries(tipsRoot)) {
      const trigger = node?.adminDemo?.generateTrigger;
      if (!trigger?.createdAt) continue;
      if (trigger.status === "done" || trigger.status === "failed") continue;

      const ageMs = nowMs - Number(trigger.createdAt || 0);
      const stuck = tipsAdminTriggerStuck(trigger, nowMs);
      const oldEnough = ageMs >= TIPS_ADMIN_POLLER_MIN_AGE_MS;
      if (!stuck && !oldEnough) continue;
      if (trigger.status === "running" && !stuck) continue;

      try {
        const result = await processTipsAdminTrigger(
          db,
          ownerUid,
          trigger,
          openaiApiKey.value()
        );
        if (result?.ok) {
          processed += 1;
          notified += Number(result.sent || 0);
          console.log(
            `tips admin poll ${ownerUid} kind=${result.kind} fcm=${result.sent}`
          );
        }
      } catch (error) {
        console.warn(
          `tips admin poll failed ${ownerUid}:`,
          error?.message || error
        );
      }
    }
    return { processed, notified };
  }
);
