import { StyleSheet } from "react-native";
import { lightColors } from "../../theme/colors";

export function createKilosaveStyles(c = lightColors) {
  const ORANGE = c.primary;
  const INK = c.text;
  const MUTED = c.textSecondary;
  const BORDER = c.border;
  const TAB_BG = c.backgroundMuted;
  const isDark = c.mode === "dark";

  return StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: c.background,
  },
  content: {
    flex: 1,
    paddingHorizontal: 18,
  },
  scrollContent: {
    paddingBottom: 40,
    gap: 14,
  },
  title: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 32,
    fontWeight: "700",
    letterSpacing: -0.7,
    textAlign: "center",
    marginTop: 2,
    marginBottom: 12,
  },

  // Figma: one pill with active segment inside
  tabBar: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: c.card,
    padding: 4,
    marginBottom: 6,
  },
  tabItem: {
    flex: 1,
    minHeight: 38,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  tabItemActive: {
    backgroundColor: c.tabActiveBg,
  },
  tabLabel: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    fontWeight: "600",
  },
  tabLabelActive: {
    color: c.tabActiveText,
  },

  card: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: c.card,
    padding: 16,
  },
  cardGap: {
    gap: 10,
  },
  cardTitle: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: -0.3,
  },
  cardRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  link: {
    color: ORANGE,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    fontWeight: "500",
    textDecorationLine: "underline",
    marginTop: 4,
  },
  muted: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    lineHeight: 18,
  },
  mutedCenter: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  italicNote: {
    color: c.textMuted,
    fontFamily: "Roobert TRIAL",
    fontSize: 11,
    fontStyle: "italic",
    lineHeight: 16,
    marginTop: 4,
  },

  primaryBtn: {
    minHeight: 46,
    borderRadius: 12,
    backgroundColor: ORANGE,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  primaryBtnCenter: {
    alignSelf: "center",
    minHeight: 44,
    minWidth: 168,
    borderRadius: 12,
    backgroundColor: ORANGE,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 22,
  },
  primaryBtnSm: {
    minHeight: 38,
    borderRadius: 10,
    backgroundColor: ORANGE,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  primaryBtnText: {
    color: c.onPrimary,
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: "600",
  },
  placeholderCard: {
    alignItems: "stretch",
  },
  placeholderText: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
    paddingVertical: 4,
  },

  // Progress
  progressTrack: {
    height: 10,
    borderRadius: 99,
    backgroundColor: c.backgroundMuted,
    justifyContent: "center",
    marginTop: 4,
    position: "relative",
    overflow: "visible",
  },
  progressFill: {
    height: 8,
    borderRadius: 99,
    backgroundColor: ORANGE,
    alignSelf: "flex-start",
  },
  progressDot: {
    position: "absolute",
    top: 0,
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: ORANGE,
    borderWidth: 1.5,
    borderColor: c.card,
  },

  statsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    marginTop: 6,
  },
  statCol: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    paddingVertical: 4,
  },
  statDivider: {
    width: 1,
    backgroundColor: BORDER,
    marginVertical: 2,
  },
  statValue: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 18,
    fontWeight: "700",
  },
  statLabel: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 11,
  },

  sectionTitle: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
    fontWeight: "700",
    marginTop: 6,
    marginBottom: 2,
  },

  weekCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 58,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BORDER,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: c.card,
  },
  weekTitle: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 15,
    fontWeight: "700",
  },
  weekMeta: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    marginTop: 2,
  },
  pending: {
    color: c.textMuted,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    fontWeight: "600",
  },
  savedAmount: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: "700",
    textAlign: "right",
  },
  savedTag: {
    color: "#16A34A",
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "right",
    marginTop: 2,
  },

  // Empty goals
  emptyWrap: {
    alignItems: "center",
    paddingTop: 28,
    paddingBottom: 8,
    gap: 16,
  },
  emptyBulb: {
    width: 96,
    height: 96,
  },
  emptyBtn: {
    minWidth: 180,
    minHeight: 46,
    borderRadius: 10,
    backgroundColor: ORANGE,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
  },

  howCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: c.card,
    padding: 18,
    gap: 16,
    marginTop: 8,
  },
  howTitle: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 17,
    fontWeight: "700",
  },
  howRow: {
    flexDirection: "row",
    gap: 12,
    alignItems: "flex-start",
  },
  howBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: ORANGE,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  howBadgeText: {
    color: c.onPrimary,
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    fontWeight: "700",
  },
  howStepTitle: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: "700",
  },
  howStepBody: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },

  warnBox: {
    flexDirection: "row",
    gap: 8,
    alignItems: "flex-start",
    borderRadius: 10,
    backgroundColor: c.warnBg,
    borderWidth: 1,
    borderColor: c.warnBorder,
    padding: 12,
    marginTop: 4,
  },
  warnText: {
    flex: 1,
    color: c.warnText,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    lineHeight: 18,
  },

  streakBox: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
    borderRadius: 12,
    backgroundColor: c.primarySoft,
    borderWidth: 1,
    borderColor: isDark ? "#5A3A28" : "#FFE1D3",
    padding: 14,
  },
  streakTitle: {
    color: ORANGE,
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: "700",
  },
  streakBody: {
    color: ORANGE,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 2,
  },

  reminderAmount: {
    color: ORANGE,
    fontFamily: "Roobert TRIAL",
    fontSize: 36,
    fontWeight: "700",
    letterSpacing: -0.8,
    marginTop: 2,
  },

  goalToggleRow: {
    flexDirection: "row",
    gap: 10,
  },
  goalToggle: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: c.card,
    alignItems: "center",
    justifyContent: "center",
  },
  goalToggleOn: {
    backgroundColor: ORANGE,
    borderColor: ORANGE,
  },
  goalToggleText: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    fontWeight: "600",
  },
  goalToggleTextOn: {
    color: c.onPrimary,
  },

  noteBox: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: TAB_BG,
    padding: 14,
  },
  noteText: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    lineHeight: 17,
  },

  promoCard: {
    borderRadius: 14,
    overflow: "hidden",
    minHeight: 132,
    backgroundColor: isDark ? c.card : "#2A241F",
    borderWidth: 1,
    borderColor: isDark ? BORDER : "#3A322C",
  },
  promoImage: {
    ...StyleSheet.absoluteFillObject,
    width: "100%",
    height: "100%",
    opacity: isDark ? 0.35 : 1,
  },
  promoOverlay: {
    flex: 1,
    minHeight: 132,
    padding: 16,
    justifyContent: "space-between",
  },
  promoText: {
    color: isDark ? INK : "#FFFFFF",
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
    maxWidth: "82%",
  },
  promoBtn: {
    alignSelf: "flex-end",
    backgroundColor: isDark ? ORANGE : "#FFFFFF",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginTop: 12,
  },
  promoBtnText: {
    color: isDark ? c.onPrimary : INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    fontWeight: "600",
  },

  periodHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  prevRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 7,
  },
  prevLabel: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
  },
  prevValue: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    fontWeight: "600",
  },

  billHint: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    lineHeight: 18,
    marginTop: 8,
  },
  billSummaryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: BORDER,
  },
  billSummaryLabel: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
  },
  billSummaryValue: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    fontWeight: "600",
  },
  billInputRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginTop: 12,
    marginBottom: 8,
  },
  statementBlock: {
    marginTop: 4,
    gap: 10,
  },
  statementField: {
    gap: 6,
  },
  statementLabel: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  statementDateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statementDateInput: {
    flex: 1,
    height: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: c.card,
    textAlign: "center",
    color: INK,
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 18,
    fontWeight: "600",
  },
  statementDateSlash: {
    color: MUTED,
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 20,
    fontWeight: "600",
  },

  // Set budget
  eyebrow: {
    color: c.textMuted,
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 1.1,
    textAlign: "center",
    marginTop: 20,
  },
  amountRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "center",
    gap: 8,
    marginTop: 16,
    marginBottom: 20,
  },
  peso: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 30,
    fontWeight: "700",
    marginBottom: 10,
  },
  bigAmount: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 64,
    fontWeight: "700",
    letterSpacing: -2,
  },
  presetRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 16,
  },
  preset: {
    flex: 1,
    minHeight: 42,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: c.card,
  },
  presetOn: {
    backgroundColor: ORANGE,
    borderColor: ORANGE,
  },
  presetText: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: "600",
  },
  presetTextOn: {
    color: c.onPrimary,
  },
  customGoalBtn: {
    minHeight: 44,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: c.card,
    marginBottom: 12,
  },
  customGoalBtnOn: {
    borderColor: ORANGE,
    backgroundColor: c.primarySoft,
  },
  customGoalBtnText: {
    color: INK,
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 14,
    fontWeight: "600",
  },
  customGoalBtnTextOn: {
    color: ORANGE,
  },
  customGoalHint: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    textAlign: "center",
    marginBottom: 12,
    lineHeight: 18,
  },
  customAmountInput: {
    minWidth: 160,
    padding: 0,
    margin: 0,
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 64,
    fontWeight: "700",
    letterSpacing: -2,
    textAlign: "center",
  },
  disclaimer: {
    position: "relative",
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    borderRadius: 12,
    backgroundColor: c.primarySoft,
    padding: 14,
    paddingRight: 28,
    marginTop: 8,
  },
  disclaimerIcon: {
    width: 36,
    height: 36,
  },
  disclaimerText: {
    flex: 1,
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    lineHeight: 17,
    paddingRight: 8,
  },
  disclaimerClose: {
    position: "absolute",
    top: 10,
    right: 10,
    padding: 4,
  },

  // Set aside
  transferEyebrow: {
    color: c.textMuted,
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 1.1,
    textAlign: "center",
    marginTop: 12,
  },
  transferAmount: {
    color: ORANGE,
    fontFamily: "Roobert TRIAL",
    fontSize: 52,
    fontWeight: "700",
    textAlign: "center",
    letterSpacing: -1.2,
    marginTop: 10,
  },
  transferSub: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    textAlign: "center",
    marginTop: 6,
    marginBottom: 14,
  },
  whyCard: {
    flexDirection: "row",
    gap: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: BORDER,
    padding: 14,
    backgroundColor: c.card,
  },
  whyIcon: {
    width: 42,
    height: 42,
  },
  savingsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 68,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: BORDER,
    paddingHorizontal: 12,
    backgroundColor: c.card,
  },
  savingsText: {
    flex: 1,
    gap: 2,
  },
  savingsName: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 15,
    fontWeight: "700",
  },
  savingsSub: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
  },
  openBtn: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: c.card,
  },
  openBtnText: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    fontWeight: "600",
  },

  bubbleWrap: {
    minHeight: 150,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 8,
  },
  bubble: {
    borderRadius: 999,
    backgroundColor: ORANGE,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  bubbleText: {
    color: "#FFFFFF",
    fontFamily: "Roobert TRIAL",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
  highlight: {
    color: ORANGE,
    fontWeight: "700",
  },
  emptyHero: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
    paddingHorizontal: 18,
    marginTop: 4,
  },
  emptyStateWrap: {
    alignItems: "center",
    gap: 18,
    paddingTop: 12,
    width: "100%",
  },
  emptyCta: {
    minHeight: 48,
    minWidth: 210,
    paddingHorizontal: 32,
    borderRadius: 999,
    backgroundColor: ORANGE,
    alignItems: "center",
    justifyContent: "center",
  },
  circleWrap: {
    alignItems: "center",
    paddingTop: 4,
    paddingBottom: 0,
  },
  circleAmount: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 42,
    fontWeight: "700",
    letterSpacing: -1,
  },
  circleCaption: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    marginTop: 2,
  },
  goalMetaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 28,
    marginTop: -4,
  },
  goalMetaCol: {
    flex: 1,
    alignItems: "center",
    gap: 2,
  },
  goalMetaValue: {
    color: INK,
    fontFamily: "Roobert TRIAL",
    fontSize: 18,
    fontWeight: "700",
  },
  goalMetaLabel: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
  },
  successBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: "rgba(250, 239, 204, 0.2)",
    borderWidth: 1,
    borderColor: "rgba(250, 239, 204, 0.2)",
  },
  successTitle: {
    color: ORANGE,
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 20,
    fontWeight: "500",
    fontStyle: "normal",
    lineHeight: 24,
    letterSpacing: -0.72,
    marginBottom: 4,
  },
  successBody: {
    color: MUTED,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    lineHeight: 18,
  },
});
}

const styles = createKilosaveStyles();
export default styles;
