import { StyleSheet } from "react-native";

export const onboardingStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  safe: {
    flex: 1,
    paddingHorizontal: 24,
  },
  body: {
    flex: 1,
    justifyContent: "center",
    gap: 28,
  },
  bodyTop: {
    flex: 1,
    paddingTop: 24,
    gap: 20,
  },
  logo: {
    width: 191,
    height: 32,
    alignSelf: "center",
    resizeMode: "contain",
  },
  welcomeCopy: {
    color: "#160600",
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
    fontWeight: "400",
    lineHeight: 24,
    letterSpacing: -0.2,
  },
  title: {
    color: "#FE6023",
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 28,
    fontWeight: "600",
    letterSpacing: -0.6,
    lineHeight: 34,
  },
  subtitle: {
    color: "#160600",
    fontFamily: "Roobert TRIAL",
    fontSize: 15,
    fontWeight: "400",
    lineHeight: 22,
    letterSpacing: -0.2,
    marginTop: 8,
  },
  footer: {
    gap: 12,
    paddingBottom: 8,
  },
  primaryBtn: {
    height: 52,
    borderRadius: 12,
    backgroundColor: "#FE6023",
    alignItems: "center",
    justifyContent: "center",
  },
  primaryBtnDisabled: {
    opacity: 0.65,
  },
  primaryBtnText: {
    color: "#FFFFFF",
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 16,
    fontWeight: "600",
  },
  secondaryBtn: {
    minHeight: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D4D4D4",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  secondaryBtnText: {
    color: "#160600",
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: "500",
    textAlign: "center",
    lineHeight: 20,
  },

  videoThumbWrap: {
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#E8E8E8",
  },
  videoThumb: {
    width: "100%",
    height: 200,
  },
  playOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(0,0,0,0.18)",
  },
  playPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: "rgba(22, 22, 22, 0.55)",
  },
  playText: {
    color: "#FFFFFF",
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 15,
    fontWeight: "600",
  },

  tipCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "#FAEFCC",
  },
  tipCardOutline: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  tipCardBill: {
    backgroundColor: "#F9EFE2",
    borderWidth: 1,
    borderColor: "#E8D9C8",
  },
  tipBulb: {
    width: 56,
    height: 56,
    resizeMode: "contain",
  },
  tipText: {
    flex: 1,
    color: "#160600",
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    fontWeight: "400",
    lineHeight: 18,
    letterSpacing: -0.2,
  },
  tipBold: {
    fontFamily: "Roobert TRIAL Medium",
    fontWeight: "600",
  },

  fieldLabel: {
    color: "#160600",
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  billDateBlock: {
    gap: 10,
  },
  billDateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  billDateInput: {
    flex: 1,
    height: 52,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D4D4D4",
    backgroundColor: "#FFFFFF",
    paddingHorizontal: 16,
    color: "#160600",
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
    textAlign: "center",
  },
  billDateSlash: {
    color: "#160600",
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 22,
    fontWeight: "600",
  },

  providerCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E8E8E8",
    backgroundColor: "#FFFFFF",
    padding: 16,
    gap: 10,
  },
  providerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  providerName: {
    color: "#160600",
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 16,
    fontWeight: "600",
  },
  selectOther: {
    color: "#6A6C6A",
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    fontWeight: "400",
  },
  rateValue: {
    color: "#FE6023",
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 36,
    fontWeight: "600",
    letterSpacing: -0.8,
  },
  rateHint: {
    color: "#6A6C6A",
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
  },
  customInput: {
    marginTop: 4,
    height: 48,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#D4D4D4",
    paddingHorizontal: 14,
    color: "#160600",
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
  },

  permissionCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#E8E8E8",
    backgroundColor: "#FFFFFF",
    padding: 16,
    gap: 12,
  },
  permissionCopy: {
    gap: 6,
  },
  permissionTitle: {
    color: "#160600",
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 16,
    fontWeight: "600",
  },
  permissionDescription: {
    color: "#6A6C6A",
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    lineHeight: 18,
  },
  permissionBtn: {
    alignSelf: "flex-start",
    minWidth: 96,
    height: 40,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#FE6023",
    backgroundColor: "#FFF5F0",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  permissionBtnText: {
    color: "#FE6023",
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 14,
    fontWeight: "600",
  },
  permissionGranted: {
    alignSelf: "flex-start",
    minWidth: 96,
    height: 40,
    borderRadius: 10,
    backgroundColor: "#E8F7EF",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
  },
  permissionGrantedText: {
    color: "#0F7A4C",
    fontFamily: "Roobert TRIAL Medium",
    fontSize: 14,
    fontWeight: "600",
  },
  permissionFootnote: {
    color: "#6A6C6A",
    fontFamily: "Roobert TRIAL",
    fontSize: 12,
    lineHeight: 17,
  },
});
