import { StyleSheet } from "react-native";
import { lightColors } from "../../theme/colors";

export function createElectricityRateStyles(c = lightColors) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: c.background,
    },
    content: {
      flex: 1,
      paddingHorizontal: 18,
    },
    scrollContent: {
      paddingBottom: 40,
      gap: 24,
    },
    infoCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 14,
      paddingHorizontal: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
    },
    infoIcon: {
      width: 48,
      height: 48,
    },
    infoText: {
      flex: 1,
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      fontWeight: "400",
      lineHeight: 18,
      letterSpacing: -0.2,
    },
    section: {
      gap: 8,
    },
    sectionTitle: {
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 18,
      fontWeight: "700",
      letterSpacing: -0.4,
    },
    sectionDesc: {
      color: c.textSecondary,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      fontWeight: "400",
      lineHeight: 18,
      letterSpacing: -0.2,
    },
    providerRow: {
      marginTop: 4,
      minHeight: 50,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.borderStrong,
      backgroundColor: c.inputBg,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    providerName: {
      flex: 1,
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 16,
      fontWeight: "600",
      letterSpacing: -0.3,
    },
    selectProvider: {
      color: c.textSecondary,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      fontWeight: "400",
    },
    rateInputRow: {
      marginTop: 4,
      minHeight: 50,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.borderStrong,
      backgroundColor: c.inputBg,
      paddingHorizontal: 14,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    rateInput: {
      flex: 1,
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 18,
      fontWeight: "700",
      paddingVertical: 10,
    },
    rateSuffix: {
      color: c.textSecondary,
      fontFamily: "Roobert TRIAL",
      fontSize: 14,
      fontWeight: "400",
    },
    exampleText: {
      color: c.textMuted,
      fontFamily: "Roobert TRIAL",
      fontSize: 12,
      marginTop: 6,
    },
    changeButtonWrap: {
      alignItems: "flex-end",
    },
    changeButton: {
      minHeight: 44,
      borderRadius: 8,
      backgroundColor: c.primary,
      paddingHorizontal: 16,
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
    },
    changeButtonDisabled: {
      opacity: 0.55,
    },
    changeButtonText: {
      color: "#FFFFFF",
      fontFamily: "Roobert TRIAL",
      fontSize: 14,
      fontWeight: "600",
      letterSpacing: -0.3,
    },
    faqList: {
      gap: 18,
      paddingTop: 4,
    },
    faqItem: {
      gap: 6,
    },
    faqTitle: {
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 15,
      fontWeight: "700",
      letterSpacing: -0.3,
    },
    faqBody: {
      color: c.textSecondary,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      fontWeight: "400",
      lineHeight: 19,
      letterSpacing: -0.2,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: c.overlay,
      justifyContent: "center",
      paddingHorizontal: 18,
    },
    modalCard: {
      backgroundColor: c.card,
      borderRadius: 16,
      paddingHorizontal: 18,
      paddingTop: 22,
      paddingBottom: 18,
      maxHeight: "88%",
      borderWidth: 1,
      borderColor: c.border,
    },
    modalTitle: {
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 20,
      fontWeight: "700",
      letterSpacing: -0.4,
      marginBottom: 16,
    },
    providerList: {
      gap: 10,
    },
    providerOption: {
      minHeight: 56,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      paddingHorizontal: 12,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    providerLogo: {
      width: 40,
      height: 40,
    },
    providerOptionText: {
      flex: 1,
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 15,
      fontWeight: "600",
      letterSpacing: -0.3,
    },
    modalHint: {
      marginTop: 16,
      color: c.textSecondary,
      fontFamily: "Roobert TRIAL",
      fontSize: 12,
      fontWeight: "400",
      lineHeight: 17,
      textAlign: "center",
    },
    confirmBody: {
      gap: 18,
      paddingBottom: 24,
    },
    confirmLead: {
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 16,
      fontWeight: "400",
      lineHeight: 24,
      letterSpacing: -0.3,
    },
    confirmHighlight: {
      color: c.primary,
      fontWeight: "700",
    },
    confirmWarning: {
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 14,
      fontWeight: "400",
      lineHeight: 20,
      letterSpacing: -0.2,
    },
    verifyTitle: {
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 15,
      fontWeight: "700",
      marginBottom: 8,
    },
    bulletRow: {
      flexDirection: "row",
      gap: 8,
      marginBottom: 6,
    },
    bulletDot: {
      color: c.text,
      fontSize: 14,
      lineHeight: 20,
    },
    bulletText: {
      flex: 1,
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 14,
      fontWeight: "400",
      lineHeight: 20,
    },
    checkboxRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      marginTop: 6,
    },
    checkbox: {
      width: 20,
      height: 20,
      borderRadius: 4,
      borderWidth: 1.5,
      borderColor: c.borderStrong,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.inputBg,
    },
    checkboxChecked: {
      borderColor: c.primary,
      backgroundColor: c.primary,
    },
    checkboxMark: {
      color: "#FFFFFF",
      fontSize: 12,
      fontWeight: "700",
    },
    checkboxLabel: {
      flex: 1,
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 14,
      fontWeight: "400",
      lineHeight: 20,
    },
    saveButton: {
      marginTop: 8,
      minHeight: 48,
      borderRadius: 8,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
      paddingHorizontal: 24,
    },
    saveButtonDisabled: {
      opacity: 0.55,
    },
    saveButtonText: {
      color: "#FFFFFF",
      fontFamily: "Roobert TRIAL",
      fontSize: 16,
      fontWeight: "600",
      letterSpacing: -0.4,
    },
    tipCard: {
      marginTop: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 14,
      paddingHorizontal: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
    },
    tipIcon: {
      width: 44,
      height: 44,
    },
    tipText: {
      flex: 1,
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      fontWeight: "400",
      lineHeight: 18,
      letterSpacing: -0.2,
    },
    errorText: {
      color: c.danger,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      marginTop: 4,
    },
  });
}

const styles = createElectricityRateStyles();
export default styles;
