import { StyleSheet } from "react-native";
import { lightColors } from "../../theme/colors";

export function createPeopleStyles(c = lightColors) {
  return StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: c.background,
  },
  content: {
    flex: 1,
    paddingHorizontal: 18,
  },
  scrollContent: {
    paddingBottom: 32,
    flexGrow: 1,
  },
  title: {
    color: c.text,
    fontFamily: "Roobert TRIAL",
    fontSize: 34,
    fontWeight: "700",
    letterSpacing: -0.8,
    textAlign: "center",
    marginTop: 8,
    marginBottom: 22,
  },
  memberList: {
    gap: 12,
  },
  memberCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    minHeight: 72,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.card,
  },
  memberCardSelected: {
    borderColor: c.primary,
    backgroundColor: c.primarySoft,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: c.backgroundMuted,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  avatarImage: {
    width: 40,
    height: 40,
  },
  avatarInitials: {
    color: c.text,
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: "700",
  },
  memberInfo: {
    flex: 1,
    gap: 2,
  },
  memberName: {
    color: c.text,
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: -0.3,
  },
  memberStatus: {
    color: c.textSecondary,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    fontWeight: "400",
  },
  roleButton: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.borderStrong,
    backgroundColor: c.mode === "dark" ? "#2C2C2C" : c.backgroundMuted,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  roleButtonText: {
    color: c.text,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    fontWeight: "600",
  },
  helperText: {
    marginTop: 14,
    color: c.textSecondary,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    lineHeight: 18,
  },
  tipCard: {
    marginTop: "auto",
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.card,
  },
  tipIcon: {
    width: 36,
    height: 36,
  },
  tipText: {
    flex: 1,
    color: c.text,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    lineHeight: 18,
  },
  tipClose: {
    padding: 4,
  },
  removeBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 16,
    marginBottom: 8,
  },
  removeButton: {
    flex: 1,
    minHeight: 44,
    borderRadius: 8,
    backgroundColor: c.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  removeButtonDisabled: {
    opacity: 0.5,
  },
  removeButtonText: {
    color: c.onPrimary,
    fontFamily: "Roobert TRIAL",
    fontSize: 15,
    fontWeight: "600",
  },
  // Role dropdown modal
  dropdownOverlay: {
    flex: 1,
    backgroundColor: c.overlay,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  dropdownCard: {
    minWidth: 160,
    backgroundColor: c.mode === "dark" ? "#2C2C2C" : "#FFFFFF",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.borderStrong,
    paddingVertical: 8,
    paddingHorizontal: 4,
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  dropdownItem: {
    minHeight: 44,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  dropdownItemText: {
    color: c.text,
    fontFamily: "Roobert TRIAL",
    fontSize: 15,
    fontWeight: "500",
  },
  // Invite screen
  inviteLead: {
    color: c.text,
    fontFamily: "Roobert TRIAL",
    fontSize: 22,
    fontWeight: "700",
    lineHeight: 30,
    letterSpacing: -0.4,
    marginTop: 18,
    marginBottom: 20,
  },
  inviteInput: {
    minHeight: 50,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: c.borderStrong,
    paddingHorizontal: 14,
    color: c.text,
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
  },
  inviteBottom: {
    marginTop: "auto",
    paddingBottom: 24,
  },
  primaryButton: {
    minHeight: 48,
    borderRadius: 8,
    backgroundColor: c.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    paddingHorizontal: 24,
  },
  primaryButtonDisabled: {
    opacity: 0.7,
  },
  primaryButtonText: {
    color: c.onPrimary,
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
    fontWeight: "600",
  },
  errorText: {
    color: c.danger,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    marginTop: 8,
  },
  // Invitation card on Settings
  invitationsSection: {
    marginBottom: 18,
    gap: 10,
  },
  invitationsTitle: {
    color: c.text,
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
    fontWeight: "700",
    letterSpacing: -0.3,
  },
  inviteCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: c.border,
    backgroundColor: c.card,
    padding: 14,
    gap: 12,
  },
  inviteCardTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  inviteCardTextWrap: {
    flex: 1,
    gap: 2,
  },
  inviteCardTitle: {
    color: c.text,
    fontFamily: "Roobert TRIAL",
    fontSize: 16,
    fontWeight: "700",
  },
  inviteCardBody: {
    color: c.textSecondary,
    fontFamily: "Roobert TRIAL",
    fontSize: 13,
    lineHeight: 18,
  },
  acceptButton: {
    alignSelf: "flex-start",
    minHeight: 40,
    borderRadius: 8,
    backgroundColor: c.primary,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  acceptButtonText: {
    color: c.onPrimary,
    fontFamily: "Roobert TRIAL",
    fontSize: 14,
    fontWeight: "600",
  },
});
}

const styles = createPeopleStyles();
export default styles;
