import { StyleSheet } from "react-native";
import { lightColors } from "../../theme/colors";

export function createSettingsStyles(c = lightColors) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: c.background,
    },
    screenWhite: {
      flex: 1,
      backgroundColor: c.background,
    },
    profileCard: {
      alignItems: "center",
      gap: 12,
      paddingVertical: 8,
      marginBottom: 8,
    },
    profileAvatarPress: {
      position: "relative",
    },
    profileAvatar: {
      width: 96,
      height: 96,
      borderRadius: 48,
      backgroundColor: c.primarySoft,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    profileAvatarImage: {
      width: "100%",
      height: "100%",
    },
    profileAvatarInitials: {
      color: c.primary,
      fontFamily: "Roobert TRIAL",
      fontSize: 28,
      fontWeight: "700",
      letterSpacing: -0.5,
    },
    profileAvatarBadge: {
      position: "absolute",
      right: 2,
      bottom: 2,
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: c.background,
    },
    profileHint: {
      color: c.textSecondary,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      textAlign: "center",
    },
    profileActions: {
      flexDirection: "row",
      gap: 10,
      flexWrap: "wrap",
      justifyContent: "center",
    },
    profileActionBtn: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
    },
    profileActionText: {
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      fontWeight: "600",
    },
    profileActionDanger: {
      borderColor: c.danger,
    },
    profileActionDangerText: {
      color: c.danger,
    },
    content: {
      flex: 1,
      paddingHorizontal: 18,
      paddingBottom: 24,
    },
    header: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 18,
      paddingBottom: 16,
      backgroundColor: "transparent",
    },
    headerTitle: {
      flex: 1,
      textAlign: "center",
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 22,
      fontWeight: "600",
      letterSpacing: -0.5,
    },
    headerSpacer: {
      width: 40,
      height: 40,
    },
    backButton: {
      width: 40,
      height: 40,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: c.card,
    },
    backArrowWrap: {
      transform: [{ rotate: "180deg" }],
    },
    rowList: {
      gap: 12,
    },
    rowCard: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      paddingVertical: 14,
      paddingHorizontal: 14,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      minHeight: 80,
    },
    rowCardDisabled: {
      opacity: 0.55,
    },
    rowIconWrap: {
      width: 28,
      alignItems: "center",
      justifyContent: "center",
    },
    rowTextWrap: {
      flex: 1,
      gap: 2,
    },
    rowTitleRow: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      gap: 6,
    },
    rowTitle: {
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 16,
      fontWeight: "600",
      letterSpacing: -0.4,
    },
    rowSubtitle: {
      color: c.textSecondary,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      fontWeight: "400",
      lineHeight: 18,
      letterSpacing: -0.3,
    },
    verifiedText: {
      color: c.success,
      fontFamily: "Roobert TRIAL",
      fontSize: 14,
      fontWeight: "600",
    },
    footerMeta: {
      marginTop: 28,
      alignItems: "center",
      gap: 4,
    },
    footerMetaText: {
      color: c.textMuted,
      fontFamily: "Roobert TRIAL",
      fontSize: 12,
      textAlign: "center",
    },
    bottomAction: {
      marginTop: "auto",
      paddingTop: 24,
    },
    primaryButton: {
      minHeight: 48,
      borderRadius: 8,
      backgroundColor: c.primary,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
      paddingHorizontal: 24,
    },
    primaryButtonDisabled: {
      opacity: 0.7,
    },
    primaryButtonText: {
      color: "#FFFFFF",
      fontFamily: "Roobert TRIAL",
      fontSize: 16,
      fontWeight: "600",
      letterSpacing: -0.4,
    },
    textInput: {
      height: 50,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.borderStrong,
      backgroundColor: c.inputBg,
      color: c.text,
      fontFamily: "Roobert TRIAL",
      fontSize: 16,
    },
    errorText: {
      color: c.danger,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      marginTop: 8,
    },
    helperText: {
      color: c.textSecondary,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      lineHeight: 18,
      marginTop: 10,
    },
    sectionLabel: {
      color: c.textMuted,
      fontFamily: "Roobert TRIAL",
      fontSize: 12,
      fontWeight: "600",
      letterSpacing: 0.6,
      textTransform: "uppercase",
      marginBottom: 8,
      marginTop: 8,
    },
    card: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
      backgroundColor: c.card,
      padding: 16,
      marginTop: 8,
    },
    fieldLabel: {
      color: c.textSecondary,
      fontFamily: "Roobert TRIAL",
      fontSize: 13,
      fontWeight: "600",
      marginBottom: 8,
    },
    dateRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
    },
    dateInput: {
      flex: 1,
      height: 50,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: c.borderStrong,
      backgroundColor: c.inputBg,
      color: c.text,
      fontFamily: "Roobert TRIAL Medium",
      fontSize: 18,
      fontWeight: "600",
      textAlign: "center",
    },
    dateSlash: {
      color: c.text,
      fontFamily: "Roobert TRIAL Medium",
      fontSize: 22,
      fontWeight: "600",
    },
  });
}

const styles = createSettingsStyles();
export default styles;
